{{ $ports := list }}
{{ if .Values.hostNetwork }}
{{ $ports = mustAppend $ports (dict "name" "http" "port" 5244 "targetPort" 5244) }}
{{ else }}
{{ $ports = mustAppend $ports (dict "name" "http" "port" .Values.web_port.port "nodePort" .Values.web_port.port "targetPort" 5244) }}
{{ end }}
{{ $params := . }}
{{ $_ := set $params "commonService" (dict "ports" $ports ) }}
{{ if .Values.hostNetwork }}
{{ $_1 := set $params.commonService "type" "ClusterIP" }}
{{ else }}
{{ $_1 := set $params.commonService "type" "NodePort" }}
{{ end }}
{{ include "common.classes.service" $params }}