apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: common
  repository: file://../../../library/common/2207.0.0
  version: 2207.0.0
description: 代理集群外的服务
home: https://gitee.com/qwerty0007/projects
icon_url: https://truecharts.org/img/hotlink-ok/chart-icons/external-service.png
keywords:
- media
name: external-service
version: 1.0.0