apiVersion: v2
appVersion: 0.0.1
dependencies:
- name: common
  repository: file://../../../library/common/2207.0.0
  version: 2207.0.0
description: '快速、简洁且高效的博客框架'
home: https://hexo.io/
icon: https://hexo.io/logo.svg
keywords:
- web
name: hexo
version: 1.0.38