apiVersion: v2
appVersion: 0.50.3
dependencies:
- name: common
  repository: file://../../../library/common/2207.0.0
  version: 2207.0.0
description: 自动化搞定限定条件下中文字幕下载。
home: https://github.com/allanpk716/ChineseSubFinder 
icon: https://s2.loli.net/2024/07/15/tpLrfKuJa54vo8O.png
keywords:
- tools
name: chinesesubfinder
version: 1.0.12