{{ $values := (. | mustDeepCopy) }}
{{ $_ := set $values "common" (dict "nameSuffix" "mariadb") }}
{{ include "common.deployment.common_config" $values | nindent 0 }}
spec: {{ include "common.deployment.common_spec" $values | nindent 2 }}
  template: {{ include "common.deployment.pod.metadata" $values | nindent 4 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}-mariadb
        image: {{ template "mariadb.imageName" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env: {{ include "mariadb.envVariableConfiguration" $values | nindent 10 }}
        volumeMounts: {{ include "mariadb.volumeMountsConfiguration" $values | nindent 10 }}
        ports:
        - name: mariadb-tcp
          containerPort: 3306
          protocol: TCP
      volumes: {{ include "mariadb.volumeConfiguration" $values | nindent 8 }}
