apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: ix-{{ template "common.names.fullname" . }}
subsets:
- addresses:
  - ip: {{ .Values.ip }}
  ports:
  - name: {{ template "common.names.fullname" . }}
    port: {{ .Values.port }}
    protocol: TCP