apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: ix-{{ template "common.names.fullname" . }}
spec:
  ports:
  - name: {{ template "common.names.fullname" . }}
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  sessionAffinity: None
  type: ClusterIP