{{ if eq (include "cert_helper.certAvailable" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cert_helper.secretName" . }}
  labels: {{ include "common.labels" . | nindent 4 }}
type: Opaque
data:
  certPublicKey: {{ (include "cert_helper.cert.publicKey" .) | toString | b64enc | quote }}
  certPrivateKey: {{ (include "cert_helper.cert.privateKey" .) | toString | b64enc | quote }}
{{ end }}