image:
  pullPolicy: IfNotPresent
  repository: nyanmisaka/jellyfin
  tag: v240401-amd64@sha256:f9be1dd2e245425070f17f308278245f0582a823f109b329567f37d4651b741e

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

jellyfinConfig:
  publishedServerUrl: ''
  additionalEnvs: []

jellyfinGPU: {}

jellyfinNetwork:
  webPort: 30013
  hostNetwork: false

jellyfinRunAs:
  user: 568
  group: 568

jellyfinStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  cache:
    type: ixVolume
    ixVolumeConfig:
      datasetName: cache
  transcodes:
    type: ixVolume
    ixVolumeConfig:
      datasetName: transcodes
  additionalStorages: []
